### PR TITLE
Milestone 2 -- Changes

### PR DESCRIPTION
**Pull request by emmyobonyo**
- Worked on the three screen sizes for Milestone 2

### CODE REVIEW

**Review by SajjadAhmad14 — CHANGES_REQUESTED** [review]
# Changes Required :recycle:
> "Change is inevitable. Change is constant. -Benjamin Disraeli"
## Hello, you have been doing a tremendous job so far :ok_hand:
## But there are some changes to make in order to get your project approved.

- [x] Your project does not have the same Featured stories section as the original project. Moreover, it's missing or Sponsored insights / Rankings section. Kindly refer to [this](https://web.archive.org/web/20210120125445/https://www.newsweek.com/) and make your web page exactly the same as the original one.
- [x] Column 2 of your webpage is very different from that of the original. You have not made the titles clickable links, and are missing text decoration as well. Please make it the same as shown provided page.
- [x] Column 3 is missing Opinion, Sponsored insights / Rankings, and
Free signup. You have laid them out under column 2. The font size of text, text-decoration is not as it's required. Images are not links. Please check the original page and make yours the same.
- [x] Please Fix the margin between Top Story and My Turn on the tablet viewport.
- [x]  Column 1 does not have Sponsored insights / Rankings on tablet view.  Please make it the same as the original one.
- [x] Please fix this broken image on small screen size:
broken-image
- [x]  Your page should have Sponsored insights / Rankings on the small viewport. Kindly check the original page for reference.
- [x] Signup section should be the same as the original. 
Your signup section:
yours-signup
Original signup section:
orignal-signup
- [x] README does not have a screenshot of the project, and the live link is not working. Kindly make your README more descriptive!

### Note: Kindly check [Project requirements](https://microverse.pathwright.com/library/new-technical-curriculum/177956/path/step/104328875/) again as your project does not comply with many requirements! 

### Reminder:
"As described in the [Code reviews limit Policy  ](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 code reviews left for this project."
### Happy Coding!

## You can always connect with me on slack ( @Sajjad Ahmad).

**Comment by emmyobonyo** [comment]
# Changes Made
- We made the changes to the images to Featured section and Top Story section. We added descriptive titles to the bottom left of the images. 
- We made changes to column 2 making it resemble the original and made all the relevant links active. 
- We added the relevant sections (Opinion / Sponsorship / Ranking / Free Sign Up Sections) to Column 3 of the Desktop screen. 
- We also fixed the margin between the Top Stories section and My Turn section in Tablet screens.
- Added sponsored insights to column two.
- Fixed the broken screen issue on small screens.
- Styled the Sign Up Section.
- Updated the README with images.

## Thanks for the recommendations. It made our work easier.

**Review by elisha2kyakpo1 — CHANGES_REQUESTED** [review]
Hey @emmyobonyo,**It's good that you have tried so hard to implement the changes which the previous TSE talked about**💪✔ Let's just fix few things before we can move.

- [x] All headers and images should be clickable( I mean all).
- [x] The fonts are not the same as the original, please fix that.
- [x] The app is breaking on the tablet version, please fix that as well.
- [x] Try to position text just the way they are on the origin.
- [x] The images are touching each other on the desktop, work on that. 
- [x] the readme file is missing important information about the project, like what the project is all about, how to get a copy of the project, etc.
- [x] Signup section should be the same as the original, did you forget to work on it?
- [x] Arrange the sections just the way The instructions indicate.
 **Please, before you make the next PR submission, try to compare your project with the original, take your time to ask others how your project look**
Remember that you only have one review left, so try your best, **I know you can do it**💪👈
I'm always available on Slack as elisha kyakopo for a chat, if you have any questions regarding the review.

**Comment by emmyobonyo** [comment]
## Changes Made
- I noticed some of the images and titles were not active, so we worked on them. 
- News Week uses 'Roboto Sans' as font so we changed the page to use that font. 
- The Opinion Section had too much padding on tablet screens, so we fixed that.
- Added the proper icon to the sign-up section.
- The images on the latest news section on desktop didn't have enough padding so we worked on that.

**Review by Dipeshtwis — APPROVED** [review]
# Status: Approved ✔️

## Hi @emmyobonyo  &  @lily-coder


Good job on implementing the suggested changes. your readme is looking and the content order and disposition changes to the correct place in tablet and mobile.
 Well done. 👏👏👏👏

However, I'm giving some high recommendations here which you have to implement to make it look better.

- [ ] **My turn** section is breaking at some resolution.

- At 972px, it looks like this.

Screenshot (1334)

- At 1376px, there is overlapping of text as well as I can see the text behind the images.

Screenshot (1333)

**You may close this Pull Request and merge the changes after fixing the above changes**

  
**Keep being awesome devs and good luck with your next milestone!**
---------

Cheers and Happy coding!👏👏👏

Code review by **Dipesh Kumar**
(Feel free to contact me on slack by the handle of  **deep** if you have any additional questions)
[Dipesh Kumar](https://deeptwist.tk) | [Twitter](https://twitter.com/97deepeshkumar)

**Pull request merged**
